### PR TITLE
Determine Supported Clients based on registered once

### PR DESCRIPTION
**Pull request by 6543**
as title

### CODE REVIEW

**Comment by 6543** [comment]
@gabrie30 ping - this refactor makes scm additions easyer again ...

**Comment by gabrie30** [comment]
@6543 i merged https://github.com/gabrie30/ghorg/pull/105, then attempted to merge this pr but there were a bunch of conflicts so I reverted 105. Did this need to be merged first?

**Comment by gabrie30** [comment]
I've added you as a collaborator to the repo

**Comment by 6543** [comment]
@gabrie30 no confilcts are fine, I develop & refactor things independent so reviews are easyer

and if something got merged I'll solve conficts for the others :)

**Review by gabrie30 — APPROVED** [review]

**Comment by 6543** [comment]
> I've added you as a collaborator to the repo

@gabrie30 If you give me write right's I'll cleanup the 105,105 thing ...

**Comment by 6543** [comment]
or just do:
```sh
git checkout -f master
git reset --hard HEAD~1
git push -f
```
And I'll do the rest

**Comment by gabrie30** [comment]
@6543 👍 i believe you'll need to accept the invitation first then i can update the permissions

**Comment by 6543** [comment]
@gabrie30 this was it ... I cant tell you how often I fall into this github trap :/

**Comment by gabrie30** [comment]
You're not the only one! 😆

**Pull request merged**
