### PR TITLE
Dedup Client Code

### PR DESCRIPTION
**Pull request by 6543**
just use create a function instead of having duplicated code

### CODE REVIEW

**Comment by 6543** [comment]
@gabrie30 this will make things easyer to maintain too :)

I also fixed 2 bugs with this ...

**Comment by gabrie30** [comment]
👍  thanks again @6543 !

**Comment by gabrie30** [comment]
> I also fixed 2 bugs with this ...

curious what you found

**Comment by 6543** [comment]
github: GetUserRepos   didnt filter forks if set
gitlab: GetUserRepos   didnt filter forks if set too

**Pull request merged**
