### PR TITLE
add ls command

### PR DESCRIPTION
**Pull request by gabrie30**
adds basics of new `ghorg ls` command

### CODE REVIEW

**Comment by gabrie30** [comment]
cc: @6543

**Comment by 6543** [comment]
```
> ./ghorg ls

open /home/6543/Desktop/ghorg/: no such file or directory
```

what's the aim of this subcomand?

**Comment by gabrie30** [comment]
to list all of the user/orgs you have cloned, do you have any repos cloned?

**Comment by 6543** [comment]
not on that specific PC.

Suggestion: it should not fail and instead tell the user he has no repos cloned ...

**Pull request merged**
