### PR TITLE
Add env only for reclone commands

### PR DESCRIPTION
**Pull request by gabrie30**
Fixes https://github.com/gabrie30/ghorg/issues/334

### CODE REVIEW

**Comment by gabrie30** [comment]
@vlcinsky let me know if you are able to test this on the main branch, you'll just need to clone the repo and run a go install or use the docker commands in the readme if you dont have go. If you don't have time let me know and I'll just cut a release. But I think this should fix your issue you'll just need to run

```
export GHORG_GITLAB_TOKEN=secret-value-here
export GHORG_RECLONE_PATH=$PWD/reclone.yaml
export GHORG_SCM_TYPE=gitlab
export GHORG_BACKUP=1
export GHORG_CLONE_WIKI=1
export GHORG_PRESERVE_DIRECTORY_STRUCTURE=1
export GHORG_ABSOLUTE_PATH_TO_CLONE_TO=/home/javl/backups/repos/gitlab.com

ghorg reclone --env-config-only
```

**Comment by vlcinsky** [comment]
@gabrie30 thanks a lot - it works.

I have tested it in th following scenarios:
- `reclone.yaml` defining 13 different ghorg clone commands, all commands are without any options and switches
  - call `ghorg reclone datex2 --env-config-only` to clone only single gitlab group
  - call `ghorg reclone datex2` and using env variable `GHORG_RECLONE_ENV_CONFIG_ONLY=1`: to clone just one GitLab group
  - call `ghorg reclone`  and using env variable `GHORG_RECLONE_ENV_CONFIG_ONLY=1`: to clone all 13 GitLab groups
 
To summarize the test: `ghorg reclone` allows me to do what I need.

# Discusion
Here I discuss few ideas about what could be done or how things could be done differently. Please, bear with me, I am easy with proposing things to others, but at the end of the day, it is you @gabrie30 to do the decision and I already know, I am already happy with that.

## name `--env-config-only`
The option and env variable name is a bit surprising - it sounds as if configuration via command line options (and config file) were ignored. My test shows, that using `--scm` option in `reclone.yaml` command has an effect, so command line options seem to be respected.

I would consider names such as:
- `--pass-env-config`
- `--env-config`
- `--pass-env`
Note, that the word `config` might make some people think, you are going to pass an `.env` config file and this is not the intention.

## Explaining the reclone behaviour to the user
It would be great to explain the `reclone` configuration behaviour to the user. I woudl think of places such as:
- `ghorg reclone --help`
- `README.md`

Take care to explain, which env. variables are hidden/passed (do you hide just the tokens?)

## Make `ghorg reclone --env-config-only` the default behaviour
It is likely, most users are expecting that environment variables used with `ghorg clone` are usable for `ghorg reclone` without any differences.

Then it would be preferred to have default behaviour the one, most users are expecting.

Of-course, there is an issue with backward compatibility then, as the hiding of env variables for `reclone` is in place for a while.

## Make `ghorg reclone --env-config-only` the only behaviour
This would render the option `--env-config-only` obsolete.

This would be my favourite solution, but again, there is an issue of backward compatibility.

## Remove `ghorg reclone` completely
The fact is, that key value of `ghorg` comes with `ghorg clone` - and it does incredibly great job.

Comparing to that, `ghorg reclone` is not really necassary. It attempts to do some automation which is another topic and which many admins are really good at. In short, if there would be no `ghorg reclone` subcommand, the `ghorg` itself would still remain really great tool.

**Comment by gabrie30** [comment]
Thank you so much for this thoughtful feedback! I think you're right about the name its not great also I remembered more of the details about the envs getting reset after the fact. So with most envs ghorg will set a default if it does not find one set. This however doesn't happen with the SCM tokens because a default value doesn't make much sense. So I'm now wondering if only the SCM tokens need to be skipped. I'll have to go back and revisit the reclone command more, it gets tricky when users want to use different configuration for cloning different orgs of the same SCM provider. If the ENV's are set for one reclone they get passed to the next reclone command which creates a lot of strange side effects. Thats why the ENV's generally get zero'd out between reclones. These points all tie into your point about removing the reclone command I think its valid, all this complication even confuses me. It could instead be done with a script calling ghorg clone commands.

I will think about this some more, thanks again for bringing up these points!

**Comment by vlcinsky** [comment]
During my attempts to develop various CLI tools it took me a while to learn common design patterns which have good chance to meet the user's expectations.

The pattern I find in most solutions, regarding configuring the tool, relates to following priority of configuration sources - from the most to the least significant one:
- command line options
- environment variables
- configuration file(s) (with ghorg it is the `$HOME/.config/ghorg/conf.yaml`, not the `reclone.yaml` which is is rather a batch file then configuration file)
- defaults (e.g. `--scm github`)

The same options and parameters can be defined in multiple places, the order mentioned above provides very simple rule, which value would win if particular parameter appears in more than one configuration source.

One can observe such priority in tools such as:
- AWS CLI: the [Configure the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) lists 10 different sources of configuration values, the source types mentioned above are present and they follow exactly the order.
- [NGINX/Configuration Overview](https://docs.nginx.com/nginx-agent/configuration-overview/) lists the same order (not mentioning default, which is implicit)

The [Command Line Interface Guidelines](https://clig.dev/) is an excellent read and in the [configuration section](https://clig.dev/#configuration) is proposing exactly this order (going further and expecting that the configuration files can be system-wide in /etc and user specific)

I remember my first programs written in Python - I was willing to write the best code possible, catching all possible problems and trying to deal with the exception on the place it was encountered the first time.
Very soon I found myself dealing with endless details and very often my code had no chance to resolve it.

It was great relieve when I have realized, that the code shall deal only with what it can really manage and other things shall be just thrown up as an exception as it is some other process or even s person to decide what to do with that.

I think, that the attempt to write `ghorg reclone` in such a way, it prevents strange side effects, resulting from poorly set env variables, is suffering from exactly the same problem.

**Pull request merged**
